import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { getGitHubAccessToken } from '@/lib/github/auth'

export const dynamic = 'force-dynamic'

/**
 * GitHub Webhook endpoint to handle PR merge events
 * Updates comments on original PRs when README PRs are merged
 */
export async function POST(request: Request) {
  try {
    const payload = await request.json()
    const event = request.headers.get('x-github-event')

    // Only process pull_request events
    if (event !== 'pull_request') {
      return NextResponse.json({ message: 'Event ignored' }, { status: 200 })
    }

    const action = payload.action
    const pr = payload.pull_request

    // Only process when PR is merged
    if (action !== 'closed' || !pr.merged) {
      return NextResponse.json({ message: 'PR not merged, ignoring' }, { status: 200 })
    }

    const owner = pr.base.repo.owner.login
    const repo = pr.base.repo.name
    const mergedPrNumber = pr.number
    const prTitle = pr.title

    // Check if this is a README update PR
    if (!prTitle.includes('README') && !prTitle.includes('readme')) {
      return NextResponse.json({ message: 'Not a README PR, ignoring' }, { status: 200 })
    }

    // Find the original PR that triggered this README PR
    const supabase = await createClient()
    const { data: prRuns, error: dbError } = await supabase
      .from('pr_runs')
      .select('*')
      .eq('repo_full_name', `${owner}/${repo}`)
      .eq('run_type', 'readme_apply')
      .eq('status', 'pending')
      .order('created_at', { ascending: false })

    if (dbError || !prRuns || prRuns.length === 0) {
      return NextResponse.json({ message: 'No README PR relationship found' }, { status: 200 })
    }

    // Find the matching README PR
    const matchingRun = prRuns.find((run: any) => 
      run.logs?.readme_pr_number === mergedPrNumber
    )

    if (!matchingRun) {
      return NextResponse.json({ message: 'No matching README PR relationship found' }, { status: 200 })
    }

    const originalPrNumber = matchingRun.pr_number
    const commentId = matchingRun.logs?.comment_id

    if (!commentId) {
      return NextResponse.json({ message: 'No comment ID found' }, { status: 200 })
    }

    // Get GitHub token
    const { token, error: tokenError } = await getGitHubAccessToken()
    if (tokenError || !token) {
      return NextResponse.json(
        { error: 'Failed to get GitHub token' },
        { status: 401 }
      )
    }

    const headers: HeadersInit = {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
    }

    // Update the comment on the original PR
    const updatedCommentBody = `## ✅ README Update Successfully Merged

The README update pull request has been successfully merged!

**Merged PR:** [PR #${mergedPrNumber}](${pr.html_url})

The README documentation has been updated with the suggested improvements. Thank you for maintaining high-quality documentation!

---

*Generated by Code Keeper*`

    const updateCommentResponse = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/issues/comments/${commentId}`,
      {
        method: 'PATCH',
        headers: {
          ...headers,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ body: updatedCommentBody }),
        cache: 'no-store',
      }
    )

    if (updateCommentResponse.ok) {
      // Update the database record
      await supabase
        .from('pr_runs')
        .update({
          status: 'completed',
          completed_at: new Date().toISOString(),
          logs: {
            ...matchingRun.logs,
            merged_at: new Date().toISOString(),
          },
        })
        .eq('id', matchingRun.id)

      console.log('Updated README PR merge comment', {
        repo: `${owner}/${repo}`,
        original_pr: originalPrNumber,
        readme_pr: mergedPrNumber,
      })

      return NextResponse.json({
        success: true,
        message: 'Comment updated successfully',
      })
    } else {
      const errorText = await updateCommentResponse.text()
      console.error('Failed to update comment:', errorText)
      return NextResponse.json(
        { error: 'Failed to update comment' },
        { status: updateCommentResponse.status }
      )
    }
  } catch (error) {
    console.error('Error processing GitHub webhook:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}


